name: 'Run Elasticsearch'
description: 'This action spins up an Elasticsearch instance that can be accessed and used in your subsequent steps.'
author: 'elastic'

branding:
  icon: 'database'
  color: 'green'

inputs:
  stack-version:
    description: 'The version of the Elastic Stack you want to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
    DETACH: true
